# Generated by Django 2.2.3 on 2022-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb_id',
            field=models.IntegerField(default=0),
        ),
    ]
