# Generated by Django 2.2.3 on 2022-01-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_movies_imdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='original_title',
        ),
    ]
