# Generated by Django 2.2.3 on 2022-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20220117_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
