# Generated by Django 2.2.3 on 2022-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20220117_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='id',
            new_name='id_num',
        ),
    ]
