# Generated by Django 2.2.3 on 2022-01-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20220117_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='id_num',
            new_name='id',
        ),
    ]
