# Generated by Django 2.2.3 on 2022-01-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20220117_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_id',
            field=models.CharField(max_length=10),
        ),
    ]
