# Generated by Django 2.2.3 on 2022-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20220117_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
